- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Elkridge # Moffstation - This is in the upstream map pool, but we use Harmony's verion
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  - Serpentcrest
  # Moffstation - Start - Our Maps
  - Amber
  - Aspid
  - Barratry
  - Frezon
  - Meta
  - Omega
  - Prime
  - Scylla
  - Skeld
  - Wapiti
  # Moffstation - End
